/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_OpusTools */

#ifndef _Included_com_example_hellojni_OpusTools
#define _Included_com_example_hellojni_OpusTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_OpusTools
 * Method:    OpusEncInit
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_example_hellojni_OpusTools_OpusEncInit
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_example_hellojni_OpusTools
 * Method:    OpusEncoderDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hellojni_OpusTools_OpusEncoderDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellojni_OpusTools
 * Method:    OpusEncode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_hellojni_OpusTools_OpusEncode
  (JNIEnv *, jobject, jint, jshortArray, jint);

/*
 * Class:     com_example_hellojni_OpusTools
 * Method:    OpusDecInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_hellojni_OpusTools_OpusDecInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_hellojni_OpusTools
 * Method:    OpusDecoderDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hellojni_OpusTools_OpusDecoderDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellojni_OpusTools
 * Method:    OpusDecode
 * Signature: ([BI[SII)I
 */
JNIEXPORT jint JNICALL Java_com_example_hellojni_OpusTools_OpusDecode
  (JNIEnv *, jobject, jbyteArray, jint, jshortArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
